spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.27.96:3306/drugdb
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    data: classpath:init.sql
    initialization-mode: always
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:                        #表字段命名策略
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl