spring:
  datasource:
    username: sa
    password: 123456
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/.drugSystem/db
    data: classpath:init.sql
    type: com.alibaba.druid.pool.DruidDataSource
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    show-sql: true
    database: h2
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect          #指定数据库引擎为Innodb

  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true