spring:
  datasource:
    username: sa
    password: 123456
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/.drugSystem/db
    data: classpath:init.sql
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database: h2