spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/drugdb?characterEncoding=utf-8 #createDatabaseIfNotExist=true&该参数可以自动建库
    username: root
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
    data: classpath:/init.sql
    initialization-mode: always
    sql-script-encoding: UTF-8


  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect          #指定数据库引擎为Innodb
    show-sql: true
    hibernate:
      naming:                        #表字段命名策略
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
