spring:
  datasource:
    username: sa
    password: 123456
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/.drugSystem/db
    data: classpath:init.sql
    type: com.alibaba.druid.pool.DruidDataSource
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    show-sql: true
    database: h2

  ##以下是开启H2数据库的网络访问
  h2:
    console:
      enabled: true
      path: /console       #访问路径
      settings:
        web-allow-others: true